[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "write", path = "./artifacts" }]

# General
evm_version = "paris"
# Chiliz
# evm_version = "shanghai"
# Peaq
# evm_version = "london"

optimizer = true
optimizer-runs = 200
solc = "0.8.18"
via_ir = false

[profile.default.zksync]
evm_version = "prague"
